<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pencairan 8</name>
   <tag></tag>
   <elementGuidId>5b5832fd-723d-4d08-8e11-c2f765c89b6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='__BVID__167']/li[12]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d033b6ca-3c70-4770-886a-4bf50f524c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/penyaluran-wilayah</value>
      <webElementGuid>00fed592-7b1b-4e8e-bdcf-aef08d31fc6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center</value>
      <webElementGuid>2cad1338-7f2f-463d-99ea-0597b47edd89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pencairan 8 </value>
      <webElementGuid>09753e8a-7ebc-4ba5-bc14-14152bc0d5e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__167&quot;)/li[@class=&quot;nav-item&quot;]/a[@class=&quot;d-flex align-items-center&quot;]</value>
      <webElementGuid>8d264231-4332-49a1-8a5d-d8bbf69aafa0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='__BVID__167']/li[12]/a</value>
      <webElementGuid>9b6061e1-ab42-4641-a793-8ea85d6da2ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UMP'])[2]/following::a[1]</value>
      <webElementGuid>76e638b3-1ca8-404c-80af-9dc6d2da08cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval Direktur Utama'])[2]/following::a[2]</value>
      <webElementGuid>7f7debab-ba6e-4742-a799-1f4afc0cefa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval Pencairan'])[2]/preceding::a[1]</value>
      <webElementGuid>35cde955-5d4b-46fe-b354-652a88330d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/penyaluran-wilayah')]</value>
      <webElementGuid>d6eccdee-d812-4499-ab75-8816b98719d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li[12]/a</value>
      <webElementGuid>0538fa9d-3f0e-4a31-afcf-c2ce6512d8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/penyaluran-wilayah' and (text() = 'Pencairan 8 ' or . = 'Pencairan 8 ')]</value>
      <webElementGuid>4adac335-4e13-4009-86e2-3689f3cf7891</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
