<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pencairan 4</name>
   <tag></tag>
   <elementGuidId>978f3395-17f5-46ab-ad6b-d8cc9af7b124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='__BVID__118']/li[14]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>be5133b0-ae4e-4e8f-8542-e36d1ca4d1d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pencairan-cabang</value>
      <webElementGuid>0b0519a7-fc76-4fb1-925f-9158f3bf9cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center</value>
      <webElementGuid>0d543603-5a45-4370-947f-a49fb16a7f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pencairan 4 </value>
      <webElementGuid>67cf7dba-10f3-4d10-b0ec-cdddbcc1de99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__118&quot;)/li[@class=&quot;nav-item&quot;]/a[@class=&quot;d-flex align-items-center&quot;]</value>
      <webElementGuid>c417d646-8539-4aba-8e65-9f9091329162</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='__BVID__118']/li[14]/a</value>
      <webElementGuid>a4a7f93c-1437-42dc-adf8-088b37dc5cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UMP'])[1]/following::a[1]</value>
      <webElementGuid>b6ac2d6e-66bb-4f2f-9855-627bd3406eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengiriman Dana'])[1]/following::a[2]</value>
      <webElementGuid>4c055e1f-9b9e-4996-b3e1-33ed0b455b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval Pencairan'])[1]/preceding::a[1]</value>
      <webElementGuid>5f84aeda-2888-417a-8c32-7a41695fe0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pencairan-cabang')]</value>
      <webElementGuid>9adc4ece-2124-4a4f-8860-8ff84c46008b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[14]/a</value>
      <webElementGuid>6cb46ddc-a7a7-4ebd-8003-68740254c7ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/pencairan-cabang' and (text() = 'Pencairan 4 ' or . = 'Pencairan 4 ')]</value>
      <webElementGuid>eea99405-5eaf-4252-a38b-d241cdccf49c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
