<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pengajuan</name>
   <tag></tag>
   <elementGuidId>c841d685-973a-490f-a394-1797b86dfc35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__167 > li.nav-item > a.d-flex.align-items-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='__BVID__167']/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8850074a-8875-4775-93dd-c5ed1e8dc3b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wilayah-pengajuan</value>
      <webElementGuid>ee26314c-7aaa-420d-93db-7e4a4bde7786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center</value>
      <webElementGuid>9c4c107b-8155-46a3-807b-d913331022f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pengajuan</value>
      <webElementGuid>854e149a-7d00-41e3-9a28-4c1015146366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__167&quot;)/li[@class=&quot;nav-item&quot;]/a[@class=&quot;d-flex align-items-center&quot;]</value>
      <webElementGuid>fee8264a-6a88-4bc9-bf5b-9222db4007bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='__BVID__167']/li/a</value>
      <webElementGuid>f98bc360-8f7e-470e-a73a-b8f9c76cc3f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penyaluran Wilayah'])[1]/following::a[1]</value>
      <webElementGuid>dc912441-0def-4f8e-8020-d53623e2846d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approval Pencairan'])[1]/following::a[2]</value>
      <webElementGuid>b265a073-3c80-472a-b98c-32aeade17e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifikasi Berkas'])[2]/preceding::a[1]</value>
      <webElementGuid>ecc6d9c1-1cdf-450f-9378-916d14b5a39e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wilayah-pengajuan')]</value>
      <webElementGuid>8d2a572b-0d04-4000-8ef5-b46a4eee7ce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li/a</value>
      <webElementGuid>03a2ebef-6d58-4558-8a06-650b5b30fb8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wilayah-pengajuan' and (text() = 'Pengajuan' or . = 'Pengajuan')]</value>
      <webElementGuid>eed529f6-d255-463b-a682-6ace43778694</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
