<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_rumah_btn btn-icon mr-1 btn-primary btn-sm</name>
   <tag></tag>
   <elementGuidId>3f6fe00f-c5a6-4c0f-ab48-251aa29ad079</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-icon.mr-1.btn-primary.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c854f6c1-2b99-4c0d-96e2-389a2bad0091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>approve</value>
      <webElementGuid>c9d00c46-9705-4428-afe5-8dfe626783bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ffdcde3b-660b-464d-a74b-2f68f7837a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-icon mr-1 btn-primary btn-sm</value>
      <webElementGuid>0f1dd7fc-0545-43cb-9790-f1ae45e81dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refDataTable&quot;)/tbody[1]/tr[1]/td[7]/button[@class=&quot;btn btn-icon mr-1 btn-primary btn-sm&quot;]</value>
      <webElementGuid>5d328ff2-3d86-4147-af6f-791daf4e0994</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>81a0bc8c-3f2b-4dd0-8890-6d7ac0e8d88e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='refDataTable']/tbody/tr/td[7]/button</value>
      <webElementGuid>099417dc-37b2-4572-9ec8-b0d47a8cc87e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='rumah'])[1]/following::button[1]</value>
      <webElementGuid>8959ebaf-3209-4754-a22e-c70c311feb77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KELOMPOK MARGAJAYA'])[1]/following::button[1]</value>
      <webElementGuid>a686cd23-684c-4436-adcb-e53b78745741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F-PPMDKS5'])[1]/preceding::button[2]</value>
      <webElementGuid>51ad4f0c-b103-4fd7-9116-397271eda7e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor :'])[1]/preceding::button[2]</value>
      <webElementGuid>c4beabd2-27d3-4666-97b1-004b63807230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/button</value>
      <webElementGuid>a57312ad-6fd5-4d9f-98de-20ddf8ea1426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'approve' and @type = 'button']</value>
      <webElementGuid>598cde4a-fc14-4398-a38e-e0dbec24a183</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
