<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle</name>
   <tag></tag>
   <elementGuidId>9f2535a2-4708-481e-a447-28f0fa235b5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.mr-0.mr-sm-50.feather.feather-search > circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>2e7b6aae-1f78-485e-bbee-b59704f1c508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>069c8876-ff77-43f7-bc2f-9c7ea82f28f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>570f8ea0-f7f6-4eea-966a-ca7a436b3e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>b3fc19c0-19cb-49fb-be10-45a43ca47559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataPIC&quot;)/section[1]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;mb-md-0 mb-2 col-md-2 col-14&quot;]/button[@class=&quot;btn button-small-filter mr-1 btn-success btn-sm&quot;]/svg[@class=&quot;mr-0 mr-sm-50 feather feather-search&quot;]/circle[1]</value>
      <webElementGuid>7beb16c1-b1b3-4ab2-9a6d-c51ce14b6765</webElementGuid>
   </webElementProperties>
</WebElementEntity>
