<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Loading_1</name>
   <tag></tag>
   <elementGuidId>827896a5-d049-4ef0-a38c-73b07e2e33f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vs13__combobox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vs13__combobox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a0124454-0118-4ae7-a19d-6d633948f56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>ff3ed615-41fc-47d1-812d-569faf29f1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__dropdown-toggle</value>
      <webElementGuid>29e072b2-fb9c-4af8-b875-996ba36b79a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>    Loading...</value>
      <webElementGuid>31966fbc-8ef3-45d9-aeef-b6be858b9a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs13__combobox&quot;)</value>
      <webElementGuid>a41a4839-76e4-43c1-9e54-86b12af20f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vs13__combobox</value>
      <webElementGuid>dc58f103-b6b4-462b-970c-0171929f0074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>2d9ee118-51c0-4ef2-97d4-140101459cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cb587e07-cb19-4410-9810-9f272666b890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>vs13__listbox</value>
      <webElementGuid>f166c355-f4e1-4b0e-b947-afcbef959e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search for option</value>
      <webElementGuid>73d6296f-e57d-42d2-8045-c45ffba5259a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='vs13__combobox']</value>
      <webElementGuid>ef96bd24-ff10-4d08-ae7b-6fc5627d0818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pemohon']/div</value>
      <webElementGuid>a5b16c2a-079d-4f7e-875b-89623647a80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[2]</value>
      <webElementGuid>42204ce3-1bd6-4a27-8aec-a77b2aa3dd19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanpa Kemiskinan'])[1]/preceding::div[4]</value>
      <webElementGuid>920bf302-e59d-4fde-b839-dac131b45dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div</value>
      <webElementGuid>d42cc6ee-0658-41dd-9f77-9df7445442d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'vs13__combobox' and (text() = '    Loading...' or . = '    Loading...')]</value>
      <webElementGuid>9c72fec1-38e7-4fdd-862a-0da416af6b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__887']/div/span/div</value>
      <webElementGuid>a7f83b08-2da2-4b92-ace7-d0ab9686e53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::div[1]</value>
      <webElementGuid>dae11b91-3927-4d8a-bd2a-f15d98c37a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/span/div</value>
      <webElementGuid>2618a762-ffa5-4552-a2b0-536444fb7884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '     Loading...  ' or . = '     Loading...  ')]</value>
      <webElementGuid>f2058e5f-457c-4263-a63f-65c54d1c3b15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
