<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Alamat Sama</name>
   <tag></tag>
   <elementGuidId>3e46e4d5-fb5c-4d84-b1a1-881c3811b1de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkbox-group-2']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a507de88-164a-4984-a893-f80dbbee8eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>892b5c45-697c-435e-8cfc-1f41bc8a5cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Alamat Sama </value>
      <webElementGuid>51c0733e-5245-4913-b7d4-35ca42f28271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-group-2&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]</value>
      <webElementGuid>ffea2a53-187e-4525-b399-4c8ab7617cb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkbox-group-2']/div/div</value>
      <webElementGuid>0c7c3209-88e3-49b5-92ff-4c032bfe8781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak Layak'])[1]/following::div[6]</value>
      <webElementGuid>dfe9277c-433f-4355-80e2-02ea04709acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layak'])[2]/following::div[6]</value>
      <webElementGuid>3c0a6230-e625-434d-9daa-67a3f1e1dca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat'])[1]/preceding::div[2]</value>
      <webElementGuid>3e14b564-062f-45c9-b648-63033972478a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/fieldset/div/div/div/div</value>
      <webElementGuid>e5c6d5cf-292e-4093-bbc0-b4561e96c5ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Alamat Sama ' or . = ' Alamat Sama ')]</value>
      <webElementGuid>806099a4-a9d0-4ebb-8274-cfe594a1e3e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
