<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tanggal</name>
   <tag></tag>
   <elementGuidId>ee39ed09-bb17-4e2d-971e-7f051a563dd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__513__outer_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__BVID__513__outer_']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>71a85c57-5345-48ce-900e-b8a4d56ce21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>group</value>
      <webElementGuid>5c95bb76-45f4-4a08-a62b-6f44bfd1e20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b-form-btn-label-control dropdown b-form-datepicker input-small form-control d-flex h-auto align-items-stretch</value>
      <webElementGuid>546fa36f-1bb6-489b-9272-9ecaf9f9f5e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>6a407348-0ce3-4f4d-a28e-fa5719cfb716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__513__outer_</value>
      <webElementGuid>c725a778-86fa-48c2-8f8d-2fc9509e4f0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>65c80606-709b-48a4-b584-438d164e3ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>__BVID__513__value_</value>
      <webElementGuid>e8c2d490-2ae2-4bdd-82c4-62ae6f0f26a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tanggal</value>
      <webElementGuid>25d01d0a-5ffc-4537-b3c6-6deb8c2dcd59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__513__outer_&quot;)</value>
      <webElementGuid>8000e6e0-48fd-44d0-a652-1dea11453e92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='__BVID__513__outer_']</value>
      <webElementGuid>e9b62e5c-1e96-466d-b76d-8c034ad9aa56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__512']/div/div</value>
      <webElementGuid>56cc0dbf-378d-49cc-9099-6e2367886656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[1]</value>
      <webElementGuid>989818a4-2f9b-4108-8491-3fa1cf3d37e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div</value>
      <webElementGuid>99e28e9e-5367-48a2-b3ea-c1d86a5fb436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@type = 'date' and @id = '__BVID__513__outer_' and (text() = 'Tanggal' or . = 'Tanggal')]</value>
      <webElementGuid>efa610d4-e434-475a-8f0d-c67fe92db65f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
