<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Format file pdf. Ukuran maks 5 MB</name>
   <tag></tag>
   <elementGuidId>116bad7e-eed6-4877-bbd8-f423fc4c12f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span > div.row > div.col</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='__BVID__1671']/div/span/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b9bb481d-e48e-4836-8d2d-e4c465c54ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>8464fe0b-a440-4771-b062-c415326090dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Format file: pdf. Ukuran maks: 5 MB </value>
      <webElementGuid>e804248c-e05d-4a6b-83fa-cb2f71621b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__1671&quot;)/div[1]/span[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]</value>
      <webElementGuid>bd0d51f5-6ede-4673-89c8-2c29fa4bbca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__1671']/div/span/div[2]/div</value>
      <webElementGuid>7030d73b-0b20-4292-969b-78c0dc07e498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih file'])[1]/following::div[2]</value>
      <webElementGuid>b0985561-170c-4a9e-afb0-1f2f3fb87634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::div[3]</value>
      <webElementGuid>b6939d4e-ca6d-4ec4-9621-ba38f7d118ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div[2]/div</value>
      <webElementGuid>d3792274-45d9-4b29-b278-a652f1a9a2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Format file: pdf. Ukuran maks: 5 MB ' or . = ' Format file: pdf. Ukuran maks: 5 MB ')]</value>
      <webElementGuid>87339ea9-3167-49e4-b21c-f80abde64501</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
