<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Test Yayasan Cendikiawan               Loading</name>
   <tag></tag>
   <elementGuidId>cb588173-21c0-4019-80d3-72d4e07c9e69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vs6__combobox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vs6__combobox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e4dffff8-a76a-4086-98d8-1615642fb193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vs6__combobox</value>
      <webElementGuid>d7818395-4b62-4ada-8d35-2ea01bf33dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>c1c84784-5b30-4d95-9f91-aebd1f4d06e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>95bd6c3c-8731-461f-a0c7-443c2ea4fff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>vs6__listbox</value>
      <webElementGuid>ad75d00b-e7ab-48e0-8066-afa857a1e9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search for option</value>
      <webElementGuid>a877607a-f18f-4cb4-9313-3283a225c5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__dropdown-toggle</value>
      <webElementGuid>9badd97c-49a1-4988-b7ba-f6c18378e393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Test Yayasan Cendikiawan
               Loading...</value>
      <webElementGuid>3c7aa0a4-7598-4ef5-8650-06d07bc92fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs6__combobox&quot;)</value>
      <webElementGuid>ddb99321-b442-4388-9ba0-5d2e27fecc3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='vs6__combobox']</value>
      <webElementGuid>0ed9906d-ed7d-40ab-90c0-b89dc9e7fad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__525']/div/div/div</value>
      <webElementGuid>676ba93a-f35e-4da8-8849-ee2f481fbd2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[2]</value>
      <webElementGuid>fdc554c1-be92-4641-bf86-b4a1a3c690b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/fieldset/div/div/div</value>
      <webElementGuid>595fb3f6-9c2d-4246-87d1-f54ec9e61142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'vs6__combobox' and (text() = '
            Test Yayasan Cendikiawan
               Loading...' or . = '
            Test Yayasan Cendikiawan
               Loading...')]</value>
      <webElementGuid>ee310c51-0440-441c-8dd2-8392d310b71d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
