<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nama PIC      Loading.   Sorry, no matc_92944f</name>
   <tag></tag>
   <elementGuidId>daa1b6ee-d1b6-40e4-aff2-4124b9b63164</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__509 > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='__BVID__509']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>53f66ffd-e57d-4088-963d-1991bac3514a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nama PIC *     Loading...   Sorry, no matching options.  </value>
      <webElementGuid>57d8775a-b067-4ad8-ba4b-0317f5b3eb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__509&quot;)/div[1]</value>
      <webElementGuid>fd79f8f3-1678-4839-974a-c0743cd1ab2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__509']/div</value>
      <webElementGuid>425a90d1-27ad-44fb-b483-e0d164981ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form Pengajuan'])[1]/following::div[5]</value>
      <webElementGuid>36f2b96f-b9a3-4c54-b462-2e5734111cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Penerima'])[1]/following::div[11]</value>
      <webElementGuid>7eee3506-a500-432f-8446-4da23f411506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div</value>
      <webElementGuid>9d4afbc5-4869-4aa9-9444-35fb8269d471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Nama PIC *     Loading...   Sorry, no matching options.  ' or . = 'Nama PIC *     Loading...   Sorry, no matching options.  ')]</value>
      <webElementGuid>2a0f2d92-7f1c-4d7c-aad1-74b20ba9f342</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
