<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Reset_full-layout Loading</name>
   <tag></tag>
   <elementGuidId>6e6a2c63-9bab-478f-911a-61fd96159508</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.full-layout.Loading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pengajuan']/section/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4f2e3584-1a2f-47c3-856d-c546a3bf1ec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-layout Loading</value>
      <webElementGuid>11eaad54-6df3-455c-8a2d-362cc4b7cd57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pengajuan&quot;)/section[1]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;loading&quot;]/div[@class=&quot;full-layout Loading&quot;]</value>
      <webElementGuid>6c9e8075-73ef-4fa0-a4b6-b9a2ac63a573</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pengajuan']/section/div[2]/div/div/div</value>
      <webElementGuid>d30a773b-1c93-4410-afdb-c46de24e4200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::div[4]</value>
      <webElementGuid>a1cbf4fb-e38a-45fb-ab7e-3a4baa66b0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/following::div[4]</value>
      <webElementGuid>033e09de-d610-4305-949b-c2ee6806bc32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Pengajuan'])[1]/preceding::div[6]</value>
      <webElementGuid>ee3c1972-ffdd-4bcb-9da3-4c42736648ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[1]/preceding::div[7]</value>
      <webElementGuid>95fae2a8-f905-4d34-bed5-d6db1c848bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/div/div/div</value>
      <webElementGuid>16b58abd-a0a6-43fd-93d9-c45f040c9eee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
