<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_No Telepon The No Telepon field is required</name>
   <tag></tag>
   <elementGuidId>382cf772-01e7-4562-aacb-e43aa05fde3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__689 > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//fieldset[@id='__BVID__689']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>faf16f70-a15f-4086-acdb-77879013a1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No Telepon *The No Telepon field is required</value>
      <webElementGuid>75bf8cc0-2e4c-4abc-b699-0ab9a5f3c59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__689&quot;)/div[1]</value>
      <webElementGuid>1f6b2d27-faca-423a-a8d4-ed88f06eb91c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__689']/div</value>
      <webElementGuid>ac3ef402-2db6-4760-a0dd-cdaee580882f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Pendidikan Terakhir field is required'])[1]/following::div[2]</value>
      <webElementGuid>da1216cc-70c5-4156-a611-ad72500c481a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[7]/following::div[2]</value>
      <webElementGuid>24325f52-793a-42c8-9d7a-fbdc010def2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/fieldset/div</value>
      <webElementGuid>919d4468-fd43-43c4-8999-250283cd5477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'No Telepon *The No Telepon field is required' or . = 'No Telepon *The No Telepon field is required')]</value>
      <webElementGuid>e4344059-d407-4e00-895d-0efd06514196</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
