<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tambah Data_full-layout Loading</name>
   <tag></tag>
   <elementGuidId>6bdca84d-3f0d-47de-b286-29f93e7bf0e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.full-layout.Loading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dataPIC']/section/div[2]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b56c1377-cfde-43b2-b4b7-96333a14e149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>full-layout Loading</value>
      <webElementGuid>fae336e4-8b4c-4caf-8e4d-1175d5ba9f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataPIC&quot;)/section[1]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;loading&quot;]/div[@class=&quot;full-layout Loading&quot;]</value>
      <webElementGuid>485f3827-d0cd-489d-962b-ac90f202001d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dataPIC']/section/div[2]/div/div[2]/div</value>
      <webElementGuid>5b9865c4-a854-49d5-b474-237306532027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Data'])[1]/following::div[2]</value>
      <webElementGuid>2e6a768c-8c89-44b9-b3fd-1c70d33ad192</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reset'])[1]/following::div[5]</value>
      <webElementGuid>42eebbb1-410c-494d-b95c-8fd64eca60e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode PIC'])[1]/preceding::div[6]</value>
      <webElementGuid>7987ea91-bdbb-4013-806d-a57c95f205e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Ktp'])[1]/preceding::div[7]</value>
      <webElementGuid>7c52fa3a-6144-455d-a510-fe705af2a4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div</value>
      <webElementGuid>9b7651cd-71be-4aef-a15f-1e438878e7ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
