<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nomorProposal</name>
   <tag></tag>
   <elementGuidId>770d9ac3-93f5-4187-8c5c-a0356b946a5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__538</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__538']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>025375b5-fd0d-40c4-9532-7bb85cd45be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nomorProposal</value>
      <webElementGuid>b6f2209f-a680-4771-859c-4926b6823867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ad6d3b6-8469-4702-b99d-354c69514085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Proposal</value>
      <webElementGuid>b32d3283-5222-4315-9a6a-fdfeda7e17ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-small form-control</value>
      <webElementGuid>4bbbf12d-4534-4a0e-9809-573f74383d7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__538</value>
      <webElementGuid>523267da-b2e7-4546-b417-34d03fdd72f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__538&quot;)</value>
      <webElementGuid>3d55841e-aeaf-4cf9-bb5b-f4ce43b67cbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__538']</value>
      <webElementGuid>20c9735d-7f83-4b38-8507-75bbd0343220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__537']/div/input</value>
      <webElementGuid>6d6d179b-344d-46cd-a31f-63b94109a621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/fieldset/div/input</value>
      <webElementGuid>98d72c69-8bb2-46c0-8e55-886e7a3828d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nomorProposal' and @type = 'text' and @placeholder = 'Nomor Proposal' and @id = '__BVID__538']</value>
      <webElementGuid>bc777de2-f2ed-4874-992a-374135afa6b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__919']</value>
      <webElementGuid>e75ececc-6fc9-48a5-83f4-1c09feea9bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__918']/div/input</value>
      <webElementGuid>44d51428-6b0f-4eda-834a-df3c2ef43ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nomorProposal' and @type = 'text' and @placeholder = 'Nomor Proposal' and @id = '__BVID__919']</value>
      <webElementGuid>cccef909-c42e-4797-a95f-701e34a160c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__868']</value>
      <webElementGuid>0acb62fe-0ee6-4ac7-82d2-30beaf8c9ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__867']/div/input</value>
      <webElementGuid>cbebd3d5-313e-4c77-84fc-aafb35f924bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nomorProposal' and @type = 'text' and @placeholder = 'Nomor Proposal' and @id = '__BVID__868']</value>
      <webElementGuid>179b90f7-fd66-4084-8a4b-e9f10ba56ac2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
