<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__tempat_lahir</name>
   <tag></tag>
   <elementGuidId>b7f8ac70-0e7f-456d-b0e2-a8b9ef942837</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__533</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__533']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3285d62-dd24-4a9e-a84f-4b3cafbd0e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tempat_lahir</value>
      <webElementGuid>dd0b72e2-e2ea-44ee-b2c1-41e8ae4817b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e902bea8-1512-42a2-ba75-dd378f23b32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tempat Lahir</value>
      <webElementGuid>a3651fa8-dbe5-4ce1-b018-6521f15bafb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-small form-control</value>
      <webElementGuid>15834d9d-cca0-42e0-8a7f-7a377e1d4fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__533</value>
      <webElementGuid>c0a2be43-c5fa-40f5-8311-658462219f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__533&quot;)</value>
      <webElementGuid>b2c20187-db76-4494-a3c9-10599c7aa687</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__533']</value>
      <webElementGuid>b2d4095a-0d5a-4bc5-af1d-7e24f194eba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__531']/div/span/input</value>
      <webElementGuid>7d8b71e4-173a-411e-ad03-ca3584a42058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div/span/input</value>
      <webElementGuid>e0d8aea7-bf61-4c0a-8fd2-4a6c79b0c052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'tempat_lahir' and @type = 'text' and @placeholder = 'Tempat Lahir' and @id = '__BVID__533']</value>
      <webElementGuid>1b26bd72-3e29-4ab4-884a-a1d254112c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__634']</value>
      <webElementGuid>63d33281-9567-4b20-9740-255511a50477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__632']/div/span/input</value>
      <webElementGuid>5f4b9009-4c75-486a-8097-adf614e349ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'tempat_lahir' and @type = 'text' and @placeholder = 'Tempat Lahir' and @id = '__BVID__634']</value>
      <webElementGuid>5b5b1ff9-18fc-4e6b-8b45-17df029edd4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
