<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nama_lembaga</name>
   <tag></tag>
   <elementGuidId>8f5fa626-7eb1-403d-8945-4b6c988e37e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__517</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__517']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c2fb740-53ee-4f59-b7b1-a39ad7c28401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_lembaga</value>
      <webElementGuid>25f34f76-36f1-47c3-8f37-1b03163e89c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f30ac6fe-4e1d-4716-a99f-78252ffd2368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Lembaga</value>
      <webElementGuid>f31fd172-ad62-4bb7-8306-2291e22e4b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-small form-control</value>
      <webElementGuid>b395cee7-c8f0-452d-aed2-65f1dcc63aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__517</value>
      <webElementGuid>2e5769e9-d5c2-41c2-bed6-1f5b5faa7e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__517&quot;)</value>
      <webElementGuid>fd53144c-6696-48c1-a2fd-c2a97dfc8cbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__517']</value>
      <webElementGuid>9cbbcb3b-9b88-422e-bfbc-cbc6100b277d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__516']/div/input</value>
      <webElementGuid>d0d0b514-5632-441c-a120-a9e4e9d302c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>cce925cb-d4a0-4e4c-b86f-8b7a52e0ec8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nama_lembaga' and @type = 'text' and @placeholder = 'Nama Lembaga' and @id = '__BVID__517']</value>
      <webElementGuid>d2b73ef6-0509-4cf5-bb23-a941b3dff1a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
