<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nama_kegiatan</name>
   <tag></tag>
   <elementGuidId>43350251-48a7-4aec-9ddd-e06bd61d000b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__532</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__532']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b2753f1-fd31-4552-a027-55be0de6b223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_kegiatan</value>
      <webElementGuid>2541f1ee-0562-445d-8dbc-cbdafd25d37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c8a1afa5-957a-459a-b651-3cb5f0e91dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Kegiatan/Proposal</value>
      <webElementGuid>a5356a67-aafa-4263-a073-f61ff470e65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-small form-control</value>
      <webElementGuid>47f083bc-e90c-4b5c-a125-58575457fa17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__532</value>
      <webElementGuid>ad5f204d-70e2-4d48-bb90-c9aa6ca72fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__532&quot;)</value>
      <webElementGuid>1a808301-a4e6-4663-93bc-6a02f5a77c09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__532']</value>
      <webElementGuid>ef5543ee-96d9-4486-a7c4-4378625dc083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__531']/div/input</value>
      <webElementGuid>8730831b-d26a-4860-a8fa-cb963dcbaf2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>23bd24f8-553d-405a-b407-8ebc5167995c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nama_kegiatan' and @type = 'text' and @placeholder = 'Nama Kegiatan/Proposal' and @id = '__BVID__532']</value>
      <webElementGuid>1ba94ed8-ca40-47c4-945e-d725ef8c827e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__913']</value>
      <webElementGuid>6decff7a-c637-4ff4-a33a-6be7084a58f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__912']/div/input</value>
      <webElementGuid>0a18cc9d-9916-4c02-81b5-ef830976c0c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nama_kegiatan' and @type = 'text' and @placeholder = 'Nama Kegiatan/Proposal' and @id = '__BVID__913']</value>
      <webElementGuid>96b6cc4a-3bb5-48ed-9605-0ae71fe31cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__862']</value>
      <webElementGuid>18495c76-e675-4e35-853f-ed4cf4f2f6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__861']/div/input</value>
      <webElementGuid>58644e97-558b-4193-8807-0e204880d650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nama_kegiatan' and @type = 'text' and @placeholder = 'Nama Kegiatan/Proposal' and @id = '__BVID__862']</value>
      <webElementGuid>3eabe4f6-9fc2-4328-9600-27dffa531a2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
