<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nilai_ppn</name>
   <tag></tag>
   <elementGuidId>62266a02-a5de-4d69-8bc6-04493d07a8b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nilai_ppn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nilai_ppn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e9f304d-ab2c-47e7-b03d-618320a85482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a8168b04-7c0d-45df-854a-b32b2f140ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nilai_ppn</value>
      <webElementGuid>18a5f5b6-6bdd-4976-aba7-2c251bda5ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nilai PPN</value>
      <webElementGuid>a920d49b-ff3b-4731-9984-46f9bd50653f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1f700e0e-4e6b-43f6-a691-79fa1a501017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nilai_ppn&quot;)</value>
      <webElementGuid>8e4a8523-c458-4ee9-840a-7204bc6fc7ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nilai_ppn']</value>
      <webElementGuid>de1a6fa2-c1de-40af-bb69-f0cfc8a82d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__1659']/div/span/input</value>
      <webElementGuid>67fca449-e4b2-4d6c-aee9-3860c7d993fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div/span/input</value>
      <webElementGuid>cfdca235-3728-45ee-8116-67e827d92f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nilai_ppn' and @placeholder = 'Nilai PPN']</value>
      <webElementGuid>33a1ceb8-c003-4e8a-8bf6-7ea88565029c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
