<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__rt</name>
   <tag></tag>
   <elementGuidId>6c6ff85f-fa5c-4739-83d9-fddef58243d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__523</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__523']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3419b01-a59a-415a-aac0-f9a81eed7b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rt</value>
      <webElementGuid>7e8794ff-0434-42f5-a05f-fdb9b600f068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4b1220b6-78f6-40ca-8875-3ec06afcead2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>RT</value>
      <webElementGuid>e83c6438-fa3e-4cc9-a90b-eb48408e7dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-small form-control</value>
      <webElementGuid>504acb72-047e-45be-88bc-506135fb0e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__523</value>
      <webElementGuid>8651b24e-ac1d-4342-981d-79e5d30d6159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9cffbaab-9981-42f5-a6a6-6a2623f212ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__523&quot;)</value>
      <webElementGuid>ced3fd55-387e-415d-ac66-1dea8a75d4a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__523']</value>
      <webElementGuid>82a00893-94c2-4069-8b03-cb84d366a756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__522']/div/input</value>
      <webElementGuid>2f1cbe5a-cfc1-418c-bd17-f089cc2592db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/fieldset/div/input</value>
      <webElementGuid>7bbdfeb9-7037-4e3b-ba43-f95f9ebd9e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rt' and @type = 'number' and @placeholder = 'RT' and @id = '__BVID__523']</value>
      <webElementGuid>9841e254-9d24-46bf-b99f-b9cab5fce1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__554']</value>
      <webElementGuid>b43ca625-2d83-4325-b0fa-858d05ba0787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__552']/div/span/input</value>
      <webElementGuid>a04aafd7-89c4-413d-8816-06d3618331b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/fieldset/div/span/input</value>
      <webElementGuid>df16c146-1c01-45f1-b353-120dc240f86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rt' and @type = 'number' and @placeholder = 'RT' and @id = '__BVID__554']</value>
      <webElementGuid>21c3c5e5-d3d1-44b3-b7e3-e48508c2a1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__655']</value>
      <webElementGuid>26668462-584a-47a2-915c-28b0839a4617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__653']/div/span/input</value>
      <webElementGuid>a8ed95bc-aae5-469b-b72b-1d75bc901d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rt' and @type = 'number' and @placeholder = 'RT' and @id = '__BVID__655']</value>
      <webElementGuid>0441816e-10b8-4ea4-a347-fc4a44b9a59f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
