<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nilai_pph</name>
   <tag></tag>
   <elementGuidId>86320409-e2d6-4677-9418-0d5a0e388acf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nilai_pph</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nilai_pph']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56cc6edd-6daa-48fc-a591-c13d24ecef8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b00ab81-8468-482c-96c4-52d5abfe24fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nilai_pph</value>
      <webElementGuid>d91f7b30-e8ed-44da-b2fa-d86ca6ff1564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nilai PPH</value>
      <webElementGuid>60484f1e-1228-4266-b71a-15d280a4d7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9a4ae2f7-8c9c-4f53-8ce2-64afc88ed16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nilai_pph&quot;)</value>
      <webElementGuid>63de0a8d-6eaf-48b2-9ea8-840bff63a355</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nilai_pph']</value>
      <webElementGuid>0079212f-a49e-4dd5-86f6-85f9aef2d489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__1668']/div/span/input</value>
      <webElementGuid>ebe7fe25-6663-468f-81b8-1740c4890ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/fieldset/div/span/input</value>
      <webElementGuid>4431aed3-c0e4-4972-b304-e4c56b38d292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'nilai_pph' and @placeholder = 'Nilai PPH']</value>
      <webElementGuid>110cd10e-f8f5-4171-983f-02a201e7a2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__663']/div/span/input</value>
      <webElementGuid>a9cdc623-21de-45e5-bb4e-76445b531abc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
