<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nama_ibu</name>
   <tag></tag>
   <elementGuidId>8c186166-a6c5-4ec4-a117-71a00882cbe2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__539</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__539']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61955423-0662-4d82-a0fc-bf4a0388f768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nama_ibu</value>
      <webElementGuid>2019fdb5-8157-46b5-9673-5ee09920e751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b05bf74-f12f-4e4f-9c96-47915c11baf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nama Ibu Kandung</value>
      <webElementGuid>f04a574d-090e-497b-99f0-ed83ee33e210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-small form-control</value>
      <webElementGuid>00041222-7433-4162-b574-f5335d4fb08c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__539</value>
      <webElementGuid>bf3ac778-a3dc-4a22-a93d-b7e6c456e478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3a91e6e5-5d33-40d1-a33b-c5bd1812f806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__539&quot;)</value>
      <webElementGuid>3928e490-cb6f-4041-881c-205ca3334843</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__539']</value>
      <webElementGuid>aa7161d5-631c-4d62-bc8d-a372ec6b3e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__537']/div/span/input</value>
      <webElementGuid>2073569f-bef0-48bd-a6cc-4c1198a2a919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[3]/div/span/input</value>
      <webElementGuid>f805c6ad-a3d8-4243-96d6-497f1591963e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nama_ibu' and @type = 'text' and @placeholder = 'Nama Ibu Kandung' and @id = '__BVID__539']</value>
      <webElementGuid>0d989a15-13f8-4d6d-99f2-58285c04876f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__640']</value>
      <webElementGuid>b51ca16b-50f1-4e6e-851f-1c5b1cf68c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__638']/div/span/input</value>
      <webElementGuid>30aac149-d130-4a03-b61b-c4e07b1aeab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nama_ibu' and @type = 'text' and @placeholder = 'Nama Ibu Kandung' and @id = '__BVID__640']</value>
      <webElementGuid>8930d5e1-e5cc-4ce1-9125-f44bfbd6cdae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
