<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nomor_telepon</name>
   <tag></tag>
   <elementGuidId>71600e3b-e22a-4de9-bfdb-0397e7eb3ff2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__541</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__541']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f837c70d-e63f-4313-b06f-aebf5dd6aa0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nomor_telepon</value>
      <webElementGuid>d81593e2-573e-495e-9932-369c84142ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ed6ed357-9b29-4fed-9de1-6d7d61fff75d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Telepon Lokasi Bantuan</value>
      <webElementGuid>939a4c03-3e16-40f1-8e5f-f6f9aec268db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-small form-control</value>
      <webElementGuid>581538aa-2de5-460f-b127-f8628950812d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__541</value>
      <webElementGuid>0f6ccceb-f79a-4846-9690-f073ff21db4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__541&quot;)</value>
      <webElementGuid>028d42a4-731c-4bae-96cb-05d2012797b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__541']</value>
      <webElementGuid>1e76c785-8d86-470d-99b7-f62e82b6fdf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__539']/div/span/input</value>
      <webElementGuid>166f5604-aeec-455e-bb43-fef9058a72a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div/span/input</value>
      <webElementGuid>4e9667dd-b367-4031-868d-8b165b856611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nomor_telepon' and @type = 'number' and @placeholder = 'Nomor Telepon Lokasi Bantuan' and @id = '__BVID__541']</value>
      <webElementGuid>610a2451-2c91-4539-a5ba-b789ccd4c1fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__922']</value>
      <webElementGuid>e9e5dbc1-dd47-4d38-91e0-ecc246abcc84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__920']/div/span/input</value>
      <webElementGuid>22e964b1-03dd-4684-8408-20243861a6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nomor_telepon' and @type = 'number' and @placeholder = 'Nomor Telepon Lokasi Bantuan' and @id = '__BVID__922']</value>
      <webElementGuid>9c2ff643-5e8f-4bc3-932f-d4936532d988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__871']</value>
      <webElementGuid>d8324ccf-0ae5-487f-9164-0b334da61184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__869']/div/span/input</value>
      <webElementGuid>65f8d7ad-7415-4943-adad-2f441f6bfde4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nomor_telepon' and @type = 'number' and @placeholder = 'Nomor Telepon Lokasi Bantuan' and @id = '__BVID__871']</value>
      <webElementGuid>3be69aa0-c25b-49d3-8292-46b2317dcd9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__553']</value>
      <webElementGuid>51de56b2-1fc2-4369-8045-a1c2d56df1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__552']/div/input</value>
      <webElementGuid>09f8706f-aa52-4bf8-870a-44307b663f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/fieldset/div/input</value>
      <webElementGuid>9fca069c-a09d-44ea-b0aa-e91a9cf02c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nomor_telepon' and @type = 'number' and @placeholder = 'No Telepon' and @id = '__BVID__553']</value>
      <webElementGuid>ea94e2d5-1da8-4a7e-9c44-f0de915d64e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__589']</value>
      <webElementGuid>5c6b2951-d1b5-4e4d-a4a2-79c784586a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__588']/div/input</value>
      <webElementGuid>97686d0b-7ec1-4e5d-8d81-fc525eefb982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>5d5f7bdb-6e1c-4ff5-ba15-89be2435271c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nomor_telepon' and @type = 'number' and @placeholder = 'No Telepon' and @id = '__BVID__589']</value>
      <webElementGuid>b23249ad-c3c4-4009-8c38-c4322e2e349b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__690']</value>
      <webElementGuid>2a9996a9-c77a-40bb-8765-251f78f8b16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__689']/div/input</value>
      <webElementGuid>712b0b40-67b5-40a1-8941-c7301a990a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nomor_telepon' and @type = 'number' and @placeholder = 'No Telepon' and @id = '__BVID__690']</value>
      <webElementGuid>34017922-4e2f-4e93-a8f8-6cac21852a6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
