<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__kewarganegaraan</name>
   <tag></tag>
   <elementGuidId>d2de71bf-0273-4561-8cea-fa4a3d3b8375</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__542</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__542']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb11cfda-7984-46f0-9e67-9b920924be3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kewarganegaraan</value>
      <webElementGuid>d3a65273-fefc-484c-bca8-29413365d71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bec4603c-be41-423e-bfbf-a608b4634f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Kewarganegaraan</value>
      <webElementGuid>e7ed8f68-d6ea-4466-bdf6-d7898fdb3adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-small form-control</value>
      <webElementGuid>2efed8f3-fbe5-49f7-a2e3-07281a8e5df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__542</value>
      <webElementGuid>eda98946-1be4-4037-aee8-f04479278458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0409494b-b519-4dcb-a5ba-60825a403cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__542&quot;)</value>
      <webElementGuid>653f2c2c-c5a2-455e-a461-f38874b18a20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__542']</value>
      <webElementGuid>d888b928-3c10-4928-9315-1448024853f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__540']/div/span/input</value>
      <webElementGuid>5a4e1838-5b97-4947-ad3b-1aecc78a40ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset[4]/div/span/input</value>
      <webElementGuid>d1e9e9f8-0ab4-4a31-921c-984d7be074e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'kewarganegaraan' and @type = 'text' and @placeholder = 'Kewarganegaraan' and @id = '__BVID__542']</value>
      <webElementGuid>f1f6cb63-2cb3-4940-9813-339a4b019246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__643']</value>
      <webElementGuid>41720bca-6241-414c-ae14-60b761f79f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__641']/div/span/input</value>
      <webElementGuid>864fde74-9be7-41ba-9730-29e88f5500ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'kewarganegaraan' and @type = 'text' and @placeholder = 'Kewarganegaraan' and @id = '__BVID__643']</value>
      <webElementGuid>53ddca08-a4ed-480e-b595-5c0318b8e9bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
