<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__rw</name>
   <tag></tag>
   <elementGuidId>5c0e4bff-ab14-4cb9-9618-ff6f7e8fcf6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__572</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__572']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e35dee6-a5dc-43b0-a224-3b9cb31b9ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rw</value>
      <webElementGuid>3c01435f-6f63-4ae5-81d9-a5d30b7f5fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>250b1909-cb30-417a-9cbb-91844830b2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>RW</value>
      <webElementGuid>4149ced1-b382-4bc2-a1e8-488d7f0ea9ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-small form-control</value>
      <webElementGuid>bc865a74-720c-4ac1-9390-949d0bd40aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__572</value>
      <webElementGuid>76bbbef4-c91d-43dd-8652-9060ab0e4d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__572&quot;)</value>
      <webElementGuid>e143e0ba-780d-41f6-af9e-2d5961e66cbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__572']</value>
      <webElementGuid>42d89b05-371e-4152-8f51-f1a480cab062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__570']/div/span/input</value>
      <webElementGuid>8a579a3a-2504-4781-bf61-5b9738124956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/fieldset/div/span/input</value>
      <webElementGuid>aa3374b2-7a7e-4a24-a0dc-da3cdcb32204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rw' and @type = 'number' and @placeholder = 'RW' and @id = '__BVID__572']</value>
      <webElementGuid>525ebb4f-d614-471e-b7af-6a6a70ad7436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__953']</value>
      <webElementGuid>ca0148a7-3c0c-4885-8214-46f6ccc70bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__951']/div/span/input</value>
      <webElementGuid>ca48367e-df92-4761-82ef-02fe74f9a819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rw' and @type = 'number' and @placeholder = 'RW' and @id = '__BVID__953']</value>
      <webElementGuid>641e20e9-d4a1-40b6-8e14-c867cb6ba262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__902']</value>
      <webElementGuid>e05c951a-2c81-4179-8427-3c8b6e9c9aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__900']/div/span/input</value>
      <webElementGuid>d7b53d14-a4ed-4ed6-9b80-dd72a68334c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rw' and @type = 'number' and @placeholder = 'RW' and @id = '__BVID__902']</value>
      <webElementGuid>81c85ec8-d9dd-4e03-abc3-c0206270ac26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__538']</value>
      <webElementGuid>fe7af988-cde2-4a80-82f3-e7d1654049c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__537']/div/input</value>
      <webElementGuid>b3ef8541-0f09-412c-a357-3c5513030350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/span/fieldset/div/input</value>
      <webElementGuid>8f038dea-eaa1-44b4-bde1-f12d3f39f90a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rw' and @type = 'number' and @placeholder = 'RW' and @id = '__BVID__538']</value>
      <webElementGuid>d2596b54-5b07-4406-b6c4-74fa34591cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__569']</value>
      <webElementGuid>ef5357ea-0148-4972-be82-e5b5fbd8dd9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__567']/div/span/input</value>
      <webElementGuid>b0d92c1f-acae-43e3-b3e8-bda94c592092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/fieldset/div/span/input</value>
      <webElementGuid>8244dfbd-b42c-4dc1-b962-9f9cea803f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rw' and @type = 'number' and @placeholder = 'RW' and @id = '__BVID__569']</value>
      <webElementGuid>8146cad3-a154-4b09-be0a-7f83d7768726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__670']</value>
      <webElementGuid>7aa8655d-b4ad-4ad4-b9b9-da5a3c92cd78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__668']/div/span/input</value>
      <webElementGuid>b793cb63-949d-46a5-a85f-354138237321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rw' and @type = 'number' and @placeholder = 'RW' and @id = '__BVID__670']</value>
      <webElementGuid>6a3b1257-3d6a-4d73-a978-f31544badc7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
