<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__bentuk_kegiatan</name>
   <tag></tag>
   <elementGuidId>e4b40410-3af6-4d88-a714-b43591cc5ee3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__797</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__797']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98b32cee-24ae-4e51-8672-a8c86668808e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bentuk_kegiatan</value>
      <webElementGuid>a4462962-f89f-4d95-b4c3-406732e17814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e8fece4a-7d16-4cab-aa5f-0b9055d838ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-small form-control</value>
      <webElementGuid>efcaf3a6-d696-4215-9854-7e771435335f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__797</value>
      <webElementGuid>801bd715-cb20-4d5c-a323-94fb55a338f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__797&quot;)</value>
      <webElementGuid>4dbc40f1-9012-4bfc-8b45-c92d81c5643b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__797']</value>
      <webElementGuid>9d8b73d2-2a31-4fd7-ae57-12e64c33d661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__796']/div/input</value>
      <webElementGuid>f3a72dc7-4431-485e-b52e-1037dcf93c7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>2929649f-442a-4918-b653-fe05c3494bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'bentuk_kegiatan' and @type = 'text' and @id = '__BVID__797']</value>
      <webElementGuid>dad182ee-354c-429b-bf2a-b812c68580b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__1222']</value>
      <webElementGuid>7b6da863-fd79-42c6-bb5a-3952d1943ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__1221']/div/input</value>
      <webElementGuid>e7b97dde-ae8d-4c31-be6e-74bf50180d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'bentuk_kegiatan' and @type = 'text' and @id = '__BVID__1222']</value>
      <webElementGuid>c2b99b07-090f-4746-a8a8-0724d7db3648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__1117']</value>
      <webElementGuid>15f6e208-dadb-4bfa-a8f4-acb35a5907f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__1116']/div/input</value>
      <webElementGuid>121e1d25-8360-4ae7-8c21-de23d5c006c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'bentuk_kegiatan' and @type = 'text' and @id = '__BVID__1117']</value>
      <webElementGuid>ca31b2cc-b625-4432-83df-0ba0753f11ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
