<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nomor_ktp</name>
   <tag></tag>
   <elementGuidId>eb2943d3-6a93-4932-9b92-29d4ce5e111f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__513</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__513']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eee0a798-52f0-4a12-bcbc-37b5f3ecd25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nomor_ktp</value>
      <webElementGuid>c8523c4a-8460-4529-abef-02c63d8d4385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2c59740b-c69c-4ef8-9971-15ece11defbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>NIK</value>
      <webElementGuid>a3a68779-ffd3-4d8d-b3cd-8e48f8f56348</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a3cb14f3-07cf-421c-bdd2-b11374f4beef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-small mr-1 form-control is-invalid</value>
      <webElementGuid>e3fac3b2-536d-48cf-8a1b-d584f357011e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>0e89eca0-62a8-4bc8-99d9-00b9deda46cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>javascript: if (this.value.length >= this.maxLength) this.value = this.value.slice(0, this.maxLength)</value>
      <webElementGuid>97b76ef5-0277-44a6-b959-58e9beed4be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__513</value>
      <webElementGuid>889d786f-17ee-4581-9435-bdaaa69952bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__513&quot;)</value>
      <webElementGuid>66985187-2bfb-4150-a7e9-ac433a85bfd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__513']</value>
      <webElementGuid>b86b1b6a-de04-47e6-b444-5cd59a5d57aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__511']/div/span/div/input</value>
      <webElementGuid>54b2ac2c-9c9b-459a-84e0-19e104bde8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2e6503c5-0725-43be-9329-f30264d6fc9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nomor_ktp' and @type = 'number' and @placeholder = 'NIK' and @id = '__BVID__513']</value>
      <webElementGuid>a0088044-8925-4fb8-81c4-eb2396c7ff78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__614']</value>
      <webElementGuid>9a6b0ad5-5bf1-493d-812e-20227edcd66e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__612']/div/span/div/input</value>
      <webElementGuid>4dcde947-f112-4241-a711-a90104e95b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nomor_ktp' and @type = 'number' and @placeholder = 'NIK' and @id = '__BVID__614']</value>
      <webElementGuid>7b4b4898-ee47-4130-91cd-56c97c17be18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
