<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__rt</name>
   <tag></tag>
   <elementGuidId>6c6ff85f-fa5c-4739-83d9-fddef58243d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__550</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__550']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8597c55-baf5-45e5-89b1-c6daf2eb2203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rt</value>
      <webElementGuid>4a76def9-56c3-4053-8b5e-be2b876a12bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1fc8e50b-51fb-4ad6-b0b3-bfaf4c280859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>RT</value>
      <webElementGuid>4ff7f96e-1e7f-473c-86d8-3d3f301987d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-small form-control</value>
      <webElementGuid>f29a0473-d839-4368-9d62-8b2018fb3068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__550</value>
      <webElementGuid>658f3124-b269-4129-8d3a-32b8863d8d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9cffbaab-9981-42f5-a6a6-6a2623f212ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__550&quot;)</value>
      <webElementGuid>d752a8dc-460d-4ef8-b127-82d0cc87bc35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__550']</value>
      <webElementGuid>15cac693-b151-4637-92b7-edb27093588e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__548']/div/span/input</value>
      <webElementGuid>35d68c53-d31c-4d83-b0f2-388adb7156e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/fieldset/div/span/input</value>
      <webElementGuid>65605881-1274-4cad-8f90-63394ca98371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rt' and @type = 'number' and @placeholder = 'RT' and @id = '__BVID__550']</value>
      <webElementGuid>6d0e9f1e-b8ee-47b0-89e4-5dfb2575ccd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__931']</value>
      <webElementGuid>f2914408-6d1b-41e9-93b2-a5e9631bcde4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__929']/div/span/input</value>
      <webElementGuid>f6051f04-efe2-447a-a988-980fb76d9efd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rt' and @type = 'number' and @placeholder = 'RT' and @id = '__BVID__931']</value>
      <webElementGuid>35bdfe1d-2d1a-4bb2-9a78-6aa40c77ab6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__880']</value>
      <webElementGuid>8be2668f-f482-47a0-aaf5-4f82bf9de3a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__878']/div/span/input</value>
      <webElementGuid>53c034ac-43eb-43d0-a075-62c34934de1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rt' and @type = 'number' and @placeholder = 'RT' and @id = '__BVID__880']</value>
      <webElementGuid>f9939b93-8b61-4f95-9aba-892de366400b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__523']</value>
      <webElementGuid>82a00893-94c2-4069-8b03-cb84d366a756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__522']/div/input</value>
      <webElementGuid>2f1cbe5a-cfc1-418c-bd17-f089cc2592db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/fieldset/div/input</value>
      <webElementGuid>7bbdfeb9-7037-4e3b-ba43-f95f9ebd9e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rt' and @type = 'number' and @placeholder = 'RT' and @id = '__BVID__523']</value>
      <webElementGuid>9841e254-9d24-46bf-b99f-b9cab5fce1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__554']</value>
      <webElementGuid>b43ca625-2d83-4325-b0fa-858d05ba0787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__552']/div/span/input</value>
      <webElementGuid>a04aafd7-89c4-413d-8816-06d3618331b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/fieldset/div/span/input</value>
      <webElementGuid>df16c146-1c01-45f1-b353-120dc240f86a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rt' and @type = 'number' and @placeholder = 'RT' and @id = '__BVID__554']</value>
      <webElementGuid>21c3c5e5-d3d1-44b3-b7e3-e48508c2a1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__655']</value>
      <webElementGuid>26668462-584a-47a2-915c-28b0839a4617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__653']/div/span/input</value>
      <webElementGuid>a8ed95bc-aae5-469b-b72b-1d75bc901d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'rt' and @type = 'number' and @placeholder = 'RT' and @id = '__BVID__655']</value>
      <webElementGuid>0441816e-10b8-4ea4-a347-fc4a44b9a59f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
