<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__nomor_telepon</name>
   <tag></tag>
   <elementGuidId>71600e3b-e22a-4de9-bfdb-0397e7eb3ff2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__553</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__553']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5050a62c-dbae-4d50-979d-ad2daf806448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nomor_telepon</value>
      <webElementGuid>729b7bac-e43c-4f47-8800-b063ece97b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>d9cbe04b-fd73-46f7-a332-324a8fad3497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No Telepon</value>
      <webElementGuid>b7cf065d-2a5f-4aca-ba55-b4bd6592767f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-small form-control</value>
      <webElementGuid>3c06191a-ed63-40bc-9554-e58bf36d8eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__553</value>
      <webElementGuid>ba6d3c07-1712-4b31-84ff-240b99d904ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__553&quot;)</value>
      <webElementGuid>3b6a7188-b102-4ad7-8b17-ead4902b5187</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__553']</value>
      <webElementGuid>51de56b2-1fc2-4369-8045-a1c2d56df1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__552']/div/input</value>
      <webElementGuid>09f8706f-aa52-4bf8-870a-44307b663f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/fieldset/div/input</value>
      <webElementGuid>9fca069c-a09d-44ea-b0aa-e91a9cf02c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nomor_telepon' and @type = 'number' and @placeholder = 'No Telepon' and @id = '__BVID__553']</value>
      <webElementGuid>ea94e2d5-1da8-4a7e-9c44-f0de915d64e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__589']</value>
      <webElementGuid>5c6b2951-d1b5-4e4d-a4a2-79c784586a3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__588']/div/input</value>
      <webElementGuid>97686d0b-7ec1-4e5d-8d81-fc525eefb982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/input</value>
      <webElementGuid>5d5f7bdb-6e1c-4ff5-ba15-89be2435271c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nomor_telepon' and @type = 'number' and @placeholder = 'No Telepon' and @id = '__BVID__589']</value>
      <webElementGuid>b23249ad-c3c4-4009-8c38-c4322e2e349b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__690']</value>
      <webElementGuid>2a9996a9-c77a-40bb-8765-251f78f8b16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__689']/div/input</value>
      <webElementGuid>712b0b40-67b5-40a1-8941-c7301a990a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'nomor_telepon' and @type = 'number' and @placeholder = 'No Telepon' and @id = '__BVID__690']</value>
      <webElementGuid>34017922-4e2f-4e93-a8f8-6cac21852a6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
