<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Program Kerja_proposalMasyarakat</name>
   <tag></tag>
   <elementGuidId>a1ff9d5b-9f24-4ee3-8088-0afc458bc78f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__569</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='__BVID__569']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae0ff44f-8e3a-48b7-a48a-5ea83e1dc673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d34ba0c1-8deb-4b09-8236-7dbf6d7bc1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>proposalMasyarakat</value>
      <webElementGuid>add65ee7-58ac-48a2-a6e2-f97801a02a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>a450f237-1983-4e6a-be8b-99f16833e80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Proposal Masyarakat</value>
      <webElementGuid>f252da4c-3b23-42ca-824a-203d034a3e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__569</value>
      <webElementGuid>ce55bb24-c396-42f5-bc4d-b1d0063f8e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__569&quot;)</value>
      <webElementGuid>335bb6b2-7ec6-4fbe-9d34-bb42a3eb2036</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='__BVID__569']</value>
      <webElementGuid>291a7601-afde-4bd3-8951-32ddf7b00f27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__568']/div/div/input</value>
      <webElementGuid>b12dd464-6c30-4cd7-8e20-822f72ab7f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/div/div/input</value>
      <webElementGuid>04a754d2-b93e-4064-9303-c221a310bc29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'proposalMasyarakat' and @id = '__BVID__569']</value>
      <webElementGuid>a78384e8-d57c-41b5-8df6-82ade1902a0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
