<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Pilih file foto KTP</name>
   <tag></tag>
   <elementGuidId>7dcba36d-2841-400c-b65f-075a67cb6fc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.custom-file-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__BVID__592__BV_file_outer_']/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>443276a9-dbdc-4bf8-a327-d784318d9e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-browse</name>
      <type>Main</type>
      <value>Browse</value>
      <webElementGuid>ca9fa11a-d770-44ff-be5b-228a6fd5b197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-file-label</value>
      <webElementGuid>b850a82a-d32e-43d7-b442-2eef91b748a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>__BVID__592</value>
      <webElementGuid>0615ef58-33e3-4c75-b05d-2c7c4a3347eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pilih file foto KTP</value>
      <webElementGuid>e212e7b6-aef9-4edd-8ad9-a9351d0ae5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__592__BV_file_outer_&quot;)/label[@class=&quot;custom-file-label&quot;]</value>
      <webElementGuid>8a2e1332-ecf4-4ae2-bbe8-b8fbd7ec18b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__BVID__592__BV_file_outer_']/label</value>
      <webElementGuid>1ae32e02-37d9-4a0e-bc5d-d85fb5ea24f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[18]/following::label[1]</value>
      <webElementGuid>9bc8e140-b0ac-4d9e-ab71-8648aba8b74d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/label</value>
      <webElementGuid>9ce9d910-454b-4981-8599-09a0a127fc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Pilih file foto KTP' or . = 'Pilih file foto KTP')]</value>
      <webElementGuid>52c10336-d485-4476-92b0-67acbd37b430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__BVID__693__BV_file_outer_']/label</value>
      <webElementGuid>6c2f069b-90b1-49be-bdbb-cd3c57ec9685</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
