<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>11f82b60-4e72-4e3d-bd38-1fafab8fbf62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>path:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>f4ac2370-cbd0-45ae-bfbc-788309b132c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z</value>
      <webElementGuid>1300f0be-1d84-4f9a-a9de-586988695245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;refDataTable&quot;)/tbody[1]/tr[1]/td[5]/button[@class=&quot;btn button-small-success mr-1 btn-success&quot;]/svg[@class=&quot;feather feather-edit&quot;]/path[2]</value>
      <webElementGuid>c41018ce-8dfd-40f3-b278-221146cd29f4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
