<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg__feather feather-chevron-down open-indi_d0d0dd</name>
   <tag></tag>
   <elementGuidId>cd86ccce-8a63-4683-916d-516632ce0c54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.feather.feather-chevron-down.open-indicator.vs__open-indicator</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::*[name()='svg'][2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>566f0959-e1ad-490b-9cba-5aa8920cc580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>b76e5cb3-b37f-42de-8233-5d2ba51a8cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>15px</value>
      <webElementGuid>52a214d2-d54e-448c-8943-442552c9e726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>15px</value>
      <webElementGuid>a0256a7c-bd5d-431b-81f9-d97947770216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>0fbf8404-f792-4c50-879c-ec2685921f10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>df85b132-6957-4344-8631-6122231ec2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>31ed6870-9131-4f91-84a7-f16ee64c37f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>ddb4ecf3-0037-4cab-be72-1ad01b4273ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>652bd2fc-78e3-4dc1-af8b-44a6488871d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>f2a008e7-0dbb-4048-9423-40ca6a6cfbaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feather feather-chevron-down open-indicator vs__open-indicator</value>
      <webElementGuid>95bf58d1-82fc-448a-96da-333c6eda96da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>411dcaa8-0cd5-49e5-8f91-5eb8e3fdc35b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs5__combobox&quot;)/div[@class=&quot;vs__actions&quot;]/svg[@class=&quot;feather feather-chevron-down open-indicator vs__open-indicator&quot;]</value>
      <webElementGuid>af87d9a3-bb07-4c42-ba87-71f0f0b6c92e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::*[name()='svg'][2]</value>
      <webElementGuid>c752a740-9061-4b86-aaa0-fa36ea301f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>9b0551d0-67b0-4880-9760-d7ac53c278c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Kawin'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>3d16a94f-315c-4b00-a819-14e0a34d5bef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
