<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__catatan-input</name>
   <tag></tag>
   <elementGuidId>79e221a7-404b-4a51-bccc-2dd8666cd25d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#catatan-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='catatan-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>92f7c450-f2a3-44ae-bc24-00ec8097b882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>catatan-input</value>
      <webElementGuid>05b55ca0-fba6-4189-a611-c162e3f28377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Catatan wajib diisi</value>
      <webElementGuid>9db8ad83-6b90-4569-bf9b-4af3f4d1d3f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wrap</name>
      <type>Main</type>
      <value>soft</value>
      <webElementGuid>7e8cc7de-66fe-40f6-a018-a8a797474e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>65add0e9-7247-4236-8609-5e041d5c6c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;catatan-input&quot;)</value>
      <webElementGuid>f87bbd3a-3d6f-4f98-9f14-940560afe9e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='catatan-input']</value>
      <webElementGuid>e51f993e-4733-4132-bc42-d7f0aaee5371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__810']/div/textarea</value>
      <webElementGuid>7982bfa6-9ac3-4e3d-9c9a-536c2724f2be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>3b7ce229-efef-4820-a377-dce7cdc6565e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'catatan-input' and @placeholder = 'Catatan wajib diisi']</value>
      <webElementGuid>6c2859f7-7cf8-42e4-af40-39ae6254a006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__522']/div/textarea</value>
      <webElementGuid>c4b7fd12-6267-4f82-960a-1554e49a22b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__616']/div/textarea</value>
      <webElementGuid>0883fff2-647d-4ff1-83ff-1ddc261d2116</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
