<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__keterangan</name>
   <tag></tag>
   <elementGuidId>1cdef4e8-d5dc-4db8-a85b-a49dbef96004</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__1052</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='__BVID__1052']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>040bd7e4-710b-4176-8a07-630a2c8fd3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keterangan</value>
      <webElementGuid>d454e8a7-8aed-4c4a-bf17-e6d51102924a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Keterangan</value>
      <webElementGuid>eb66953f-c639-413a-814a-dbc88808791f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>69cf46d5-38f6-4ce0-bae6-a6fb67452f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wrap</name>
      <type>Main</type>
      <value>soft</value>
      <webElementGuid>39db2a54-3913-433a-812e-a08c59273734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>184767fc-979a-43ca-a70e-78a9341d2e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__1052</value>
      <webElementGuid>f75e1424-2543-4ff0-bc37-aaf86dd3829f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__1052&quot;)</value>
      <webElementGuid>63ce4f19-4595-48b6-80aa-4a586309f5fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='__BVID__1052']</value>
      <webElementGuid>3d87af2e-ce0a-4046-87b5-b12f1d25c6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__1051']/div/textarea</value>
      <webElementGuid>5021bdc7-0a63-4934-bceb-faa76fb14e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>173cfdd1-ad83-4fe0-8ec3-ce41167fff27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'keterangan' and @placeholder = 'Keterangan' and @id = '__BVID__1052']</value>
      <webElementGuid>d43939e0-2bec-4b26-a514-f5b16633d4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='__BVID__1485']</value>
      <webElementGuid>683e4ca4-afc1-4478-95ea-e158e11468fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__1484']/div/textarea</value>
      <webElementGuid>5e6a6180-22aa-4000-8190-3466f4ccc41f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'keterangan' and @placeholder = 'Keterangan' and @id = '__BVID__1485']</value>
      <webElementGuid>477304db-bb85-426f-8e92-a75e5e76a305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='__BVID__1378']</value>
      <webElementGuid>cd77851c-c330-4beb-8717-03ffe8affff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__1377']/div/textarea</value>
      <webElementGuid>f075c554-4760-4128-b14b-f3b2ca515e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'keterangan' and @placeholder = 'Keterangan' and @id = '__BVID__1378']</value>
      <webElementGuid>c511d356-43ca-4aea-bd5d-401631d4e82b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
