<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Lokasi Bantuan_lokasi_bantuan</name>
   <tag></tag>
   <elementGuidId>20abf1de-345d-4d31-ab49-95a70c03864d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#__BVID__547</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='__BVID__547']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>dcf0ab22-2099-4508-94d3-f2f1d37e7b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lokasi_bantuan</value>
      <webElementGuid>84c7dc89-3607-4de4-9343-2819a845117d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Lokasi Bantuan</value>
      <webElementGuid>a875cb93-13d0-4d1b-82ac-5d969868fb16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>360ed4be-d775-46d0-a768-5cc7fb749d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wrap</name>
      <type>Main</type>
      <value>soft</value>
      <webElementGuid>da2c4999-bd4c-485a-899a-e299f2dd0a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f05b81ca-7fd0-4085-a8b8-70759eb659c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__BVID__547</value>
      <webElementGuid>55742f33-29c2-49dc-8296-ac2d35f21c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__BVID__547&quot;)</value>
      <webElementGuid>d5d7a7b7-b927-4b45-92c6-667b2af5ca96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='__BVID__547']</value>
      <webElementGuid>55e05ff3-e6e7-42f5-9285-2d6abeac7cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__545']/div/span/textarea</value>
      <webElementGuid>6a4eb7b1-ef79-483a-ac8f-5699e2d6b4ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>872cfd5a-774f-4711-8d92-792bf8e58e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'lokasi_bantuan' and @placeholder = 'Lokasi Bantuan' and @id = '__BVID__547']</value>
      <webElementGuid>19dedf27-346e-4655-b9ae-928760c191a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='__BVID__928']</value>
      <webElementGuid>11f50f59-fb67-4dcb-a7a8-f2029ce582bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__926']/div/span/textarea</value>
      <webElementGuid>cf5c36e9-7ebb-4fb0-9a59-cadb3c94fad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'lokasi_bantuan' and @placeholder = 'Lokasi Bantuan' and @id = '__BVID__928']</value>
      <webElementGuid>21269d8e-2f12-42ba-94ea-a37c7eb43fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='__BVID__877']</value>
      <webElementGuid>7f20d77c-53c1-4c6f-b7b5-8b5a4f2cd2ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='__BVID__875']/div/span/textarea</value>
      <webElementGuid>605088f0-2f9b-4ed3-8e89-cf00a058b04d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'lokasi_bantuan' and @placeholder = 'Lokasi Bantuan' and @id = '__BVID__877']</value>
      <webElementGuid>d9a99d57-1ba6-41f9-bf20-fd7e7acd96bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
